### ISSUE TITLE
Store html files in database

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Content#5]

**Comment by dan31** [comment]
@miyconst @warpech, which files do we store in a database? I'm asking since storing real files in an in-memory database isn't a good idea in 90% of cases. But maybe you only consider some tiny parts like templates.

**Comment by warpech** [comment]
Here we are talking about static contents, which are not templates. They are actual text contents to populate the website with static text. Starcounter.io would have about 100-200 such contents (median size 3 KB).

We discussed this with @miyconst. The benefits of keeping static CMS contents in database are:

- easy import/export of the CMS data. `staradmin db unload/reload` is enough, similarly to WordPress.
- the memory impact is exactly the same as keeping static files on disk, because Starcounter's internal web server caches HTML files by default (which is desired for good performance, and also a common practice in other platforms - e.g. PHP + memcached).

**Comment by dan31** [comment]
Yeah I see, and this is how wordpress and others doing that as well. Thanks for explaining! You will not exceed tens of megabytes of DB space in memory with overall set of such files usually.

**Comment by miyconst** [comment]
Done. The html content of Content application is now saved in database. The default html items are still saved as files and loaded into database on application start.
